apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-secret
  labels:
    app: postgres
data:
  POSTGRES_DB: pdqa_dev
  POSTGRES_USER: root
  POSTGRES_PASSWORD: SecurePassword
  PGDATA: /var/lib/postgresql/data